# .hound.yml

# TypeScript configuration
eslint:
  plugins:
    - '@typescript-eslint/eslint-plugin'
  parser: '@typescript-eslint/parser'
  parserOptions:
    ecmaVersion: 2018
    sourceType: module
    ecmaFeatures:
      jsx: true
  extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
  rules:
    # Add any custom rules or overrides here
patterns:
  - '**/*.ts'
  - '**/*.tsx'

# Sass configuration
stylelint:
  config: '.stylelintrc.json'
  # You can add any additional flags or options here
  patterns:
    - '**/*.scss'
