name: Releases
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3.7.1
        with:
          github-token: $
          # skip-version-file: 'true'

      - name: create release
        uses: actions/create-release@v1
        if: $
        env:
          GITHUB_TOKEN: $
        with:
          tag_name: $
          release_name: $
          body: $
